---
abstract: 'English names of nationalities'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.96
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Nationality-en
provides:
  Locale::Nationality::en:
    file: lib/Locale/Nationality/en.pm
    version: 1.02
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 1.02
