---
abstract: Locale::Nationality::en
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.96
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Nationality-en
provides:
  Locale::Nationality::en:
    file: lib/Locale/Nationality/en.pm
    version: 1.01
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.01
